import Head from 'next/head';
import Header from '../components/header/Header';
import Main from '../components/main/Main';

export default function Home() {
  return (
    <>
      <Head>
        <title>Website for father - Storage</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,shrink-to-fit=no,viewport-fit=cover"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
    </>
  );
}
