

import Head from 'next/head';
import Header from '../components/mainPage/header/Header';
import Main from '../components/mainPage/main/Main';
import Footer from '../components/mainPage/footer/Footer';

import PageBlur from '../components/wholePageBlur/PageBlur';
import ModalMeinMenu from '../components/modalMainMenu/ModalMainMenu';
import ModalFind from '../components/modalFind/ModalFind';
import ModalPhone from '../components/modalPhone/ModalPhone';

export default function Home() {
  return (
    <>
      <Head>
        <title>Website for father - Storage</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width,initial-scale=1,shrink-to-fit=no,viewport-fit=cover"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main />
      <Footer />
      <PageBlur />
      <ModalMeinMenu />
      {/* <ModalFind /> */}
      {/* <ModalPhone /> */}
    </>
  );
}
